bdregistration/urls.py
from django.contrib import admin
from django.urls import include,  path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('cisystem.urls')),
    path('cisystem/', include('cisystem.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # new
    path('admin/', admin.site.urls),
    # path('', TemplateView.as_view(template_name='cisystem/home.html'), name='home'),  # new
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cisystem/urls.py
from django.conf.urls import url
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cisystem'
urlpatterns = [
    path('', views.index,  name='index'),
    path('about/', views.about,  name='about'),
    path('login/', views.login,  name='login'),
    path('contact/', views.contact,  name='contact'),
    path('birth_detail/', views.birth_detail,  name='birth_detail'),
    path('death_detail/', views.death_detail,  name='death_detail'),
    path('late_registration/', views.late_registration,  name='late_registration'),
    path('user_login/', views.user_login,  name='user_login'),
    path('user_error_login/', views.user_error_login,  name='user_error_login'),
    path('eligible_list/', views.get_eligible_listView.as_view(),  name='eligible_list'),
    path('vital_statistics/', views.get_vital_statistics_View.as_view(),  name='statistics'),
    path('<int:pk>/', views.userProfileView.as_view(), name='user_profile'),
    path('<int:pk>/birth_certificate/', views.birthcertificateView.as_view(), name='certificate'),
    path('<int:pk>/death_certificate/', views.deathCertificateView.as_view(), name='death_certificate_view'),
    path('birth_certificate/', views.birth_certificate, name='birth_certificate'),
    path('death_certificate/', views.death_certificate, name='death_certificate'),
    path('api/chart/data/', views.ChartData.as_view(), name='api_data'),
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cisystem/models.py
import uuid
from enum import Enum

from django.db import models
from datetime import date

# Create your models here.
from django.urls import reverse_lazy
from model_utils import Choices


class Birth(models.Model):
    registration_center = models.CharField(max_length=200)
    certificate_number = models.CharField(max_length=200, default=None, blank=True, null=True)
    town_or_village_of_registration = models.CharField(max_length=200)
    LGA_of_registration = models.CharField(max_length=200)
    state_of_registration = models.CharField(max_length=200)
    entry_no = models.IntegerField(default=None,blank=True, null=True)
    surname_of_child = models.CharField(max_length=200)
    other_name_of_child = models.CharField(max_length=200)

    class SEX (Enum):
        male = ('male', 'Male')
        female = ('female', 'Female')
        @classmethod
        def get_value(cls, members):
            return cls[members].value[0]

    sex = models.CharField(max_length=200, choices=[x.value for x in SEX], default=SEX.get_value('male'),)

    class PLACE (Enum):
        hospital = ('hospital', 'Hospital')
        maternity = ('maternity', 'Maternity')
        church = ('church', 'Church')
        home = ('home', 'Home')
        others = ('others', 'Others')
        @classmethod
        def get_value(cls, members):
            return cls[members].value[0]
    place_of_birth = models.CharField(max_length=200, choices=[x.value for x in PLACE], default=PLACE.get_value('hospital'),)
    date_of_birth = models.DateTimeField('date of birth')
    town_or_village_of_birth = models.CharField(max_length=200)

    surname_of_mother = models.CharField(max_length=200)
    Other_name_of_mother = models.CharField(max_length=200)
    residence_of_mother = models.CharField(max_length=200)
    age_of_mother_at_child_birth = models.CharField(max_length=200)
    state_of_origin_of_mother = models.CharField(max_length=200)
    ethnicity_of_mother = models.CharField(max_length=200, default=None, blank=False)

    class MOTHER_STATUS (Enum):
        married = ('married', 'Married')
        divorce = ('divorce', 'Divorce')
        seperate = ('seperate', 'Seperate')
        widow = ('widow', 'Widow')
        single = ('single', 'Single')
        @classmethod
        def get_value(cls, members):
            return cls[members].value[0]
    mother_marital_status = models.CharField(max_length=200, choices=[x.value for x in MOTHER_STATUS], default=MOTHER_STATUS.get_value('married'),)

    class MOTHER_NATIONALITY (Enum):
        nigeria = ('nigeria', 'Nigeria')
        others = ('others', 'Others')
        @classmethod
        def get_value(cls, members):
            return cls[members].value[0]
    nationality_of_mother = models.CharField(max_length=200, choices=[x.value for x in MOTHER_NATIONALITY], default=MOTHER_NATIONALITY.get_value('nigeria'),)

    occupation_of_mother = models.CharField(max_length=200)
    educational_qualification_of_mother = models.CharField(max_length=200)
    mother_phone = models.CharField(max_length=200, default=None, blank=True)
    mother_email = models.EmailField(max_length=200, default=None, blank=True)

    surname_of_father = models.CharField(max_length=200)
    other_name_of_father = models.CharField(max_length=200)
    state_of_origin_of_father = models.CharField(max_length=200)
    ethnicity_of_father = models.CharField(max_length=200)

    class FATHER_STATUS(Enum):
        married = ('married', 'Married')
        divorce = ('divorce', 'Divorce')
        seperate = ('seperate', 'Seperate')
        widow = ('widow', 'Widow')
        single = ('single', 'Single')

        @classmethod
        def get_value(cls, members):
            return cls[members].value[0]
    father_marital_status = models.CharField(max_length=200, choices=[x.value for x in FATHER_STATUS], default=FATHER_STATUS.get_value('married'),)

    class FATHER_NATIONALITY (Enum):
        nigeria = ('nigeria', 'Nigeria')
        others = ('others', 'Others')
        @classmethod
        def get_value(cls, members):
            return cls[members].value[0]
    nationality_of_father = models.CharField(max_length=200, choices=[x.value for x in FATHER_NATIONALITY], default=FATHER_NATIONALITY.get_value('nigeria'),)
    occupation_of_father = models.CharField(max_length=200)
    educational_qualification_of_father = models.CharField(max_length=200)
    phone_of_father = models.CharField(max_length=200, default=None, blank=True)
    email_of_father = models.EmailField(max_length=200, default=None, blank=True)

    relationship_with_child = models.CharField(max_length=200)
    surname_of_informant = models.CharField(max_length=200)
    other_name_of_informant = models.CharField(max_length=200)
    address_of_informant = models.CharField(max_length=200)
    phone_of_informant = models.CharField(max_length=200, default=None, blank=True)
    email_of_informant = models.CharField(max_length=200, default=None, blank=True)

    username = models.CharField(max_length=200, unique=True)
    password = models.CharField(max_length=200)
    registered_late = models.BooleanField(default=False)
    id_card = models.FileField(upload_to='uploads', default=None, blank=True, null=True)
    amount_paid = models.IntegerField(default=None, blank=True, null=True)
    registered_date = models.DateTimeField(auto_now=True)
    child_age = models.IntegerField(default=None, blank=True, null=True)
    place_of_issue = models.CharField(max_length=200,default=None, blank=False, null=False)
    name_of_registrar = models.CharField(max_length=200, default=None, blank=False, null=False)
    is_eligible = models.BooleanField(default=False)
    is_dead = models.BooleanField(default=False)

    def __str__(self):
        return self.surname_of_child

def set_entry_no(sender, instance, **kwargs):
    if not instance.entry_no:
        instance.entry_no = instance.id
    return instance.entry_no
models.signals.pre_save.connect(set_entry_no, sender=Birth)


def set_username(sender, instance, **kwargs):
        if not instance.username:
            username = instance.surname_of_child.replace(" ", "").lower()
            counter = 1
            while Birth.objects.filter(username=username):
                username = instance.surname_of_child + str(counter)
                counter += 1
            instance.username = username
models.signals.pre_save.connect(set_username, sender=Birth)


def random_password(sender, instance, **kwargs):
    if not instance.password:
        instance.password = uuid.uuid4().hex[:8]
models.signals.pre_save.connect(random_password, sender=Birth)


def set_certificate_no(sender, instance, **kwargs):
        if not instance.certificate_number:
          instance.certificate_number = uuid.uuid4().hex[:8].upper()
models.signals.pre_save.connect(set_certificate_no, sender=Birth)


def calculate_age(sender, instance, **kwargs):
    today = date.today()
    if not instance.child_age:
        instance.child_age = today.year - instance.date_of_birth.year - ((today.month, today.day) < (instance.date_of_birth.month, instance.date_of_birth.day))
    return instance.child_age
models.signals.pre_save.connect(calculate_age, sender=Birth)


def check_eligible(sender, instance, **kwargs):
    if not instance.is_eligible:
        instance.is_eligible = calculate_age(check_eligible, instance) > 17
        return instance.is_eligible
    else:
        return False
models.signals.pre_save.connect(check_eligible, sender=Birth)


class Death(models.Model):
    birth_id = models.ForeignKey(Birth, on_delete=models.CASCADE, default=None, blank=True, null=True)
    registration_center = models.CharField(max_length=200)
    town_or_village_of_registration = models.CharField(max_length=200)
    LGA_of_registration = models.CharField(max_length=200)
    state_of_registration = models.CharField(max_length=200)
    certificate_number = models.CharField(max_length=200, default=None, blank=True, null=True)

    surname_of_deceased = models.CharField(max_length=200)
    othername_of_deceased = models.CharField(max_length=200)
    class SEX (Enum):
        male = ('male', 'Male')
        female = ('female', 'Female')
        @classmethod
        def get_value(cls, members):
            return cls[members].value[0]
    sex = models.CharField(max_length=200, choices=[x.value for x in SEX], default=SEX.get_value('male'),)
    date_of_death = models.DateField(max_length=200)
    occupation_of_deceased = models.CharField(max_length=200)
    cause_of_death = models.CharField(max_length=200)
    place_of_death = models.CharField(max_length=200)
    residence_of_deceased = models.CharField(max_length=200)
    age_at_death = models.IntegerField()
    surname_of_informant = models.CharField(max_length=200)
    othername_of_informant = models.CharField(max_length=200)
    relationship_to_deceased = models.CharField(max_length=200)
    address_of_informant = models.CharField(max_length=200)
    phone_of_informant = models.CharField(max_length=200, default=None, blank=True)
    email_of_informant = models.EmailField(max_length=200)

    certified_death_by = models.CharField(max_length=200)
    place_of_issue = models.CharField(max_length=200)
    name_of_registrar = models.CharField(max_length=200)
    date_of_issue = models.DateField(max_length=200)
    name_of_doctor = models.CharField(max_length=200)
    entry_no = models.IntegerField(default=None, blank=True, null=True)
    certificate_of_origin = models.FileField(upload_to='uploads', default=None, blank=True, null=True)
    affidavit = models.FileField(upload_to='uploads', default=None, blank=True, null=True)
    proof_of_death = models.FileField(upload_to='uploads', default=None, blank=True, null=True)
    certificate_required = models.BooleanField(default=False)
    amount_paid = models.IntegerField()
    username = models.CharField(max_length=200, unique=True)
    password = models.CharField(max_length=200)

cisystem/views.py
from re import template

from django.contrib.auth import authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, redirect, render_to_response
from django.urls import reverse
from django.views import generic
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import Birth, Death


def index(request):
   return render(request, 'cisystem/index.html')

def about(request):
   return render(request, 'cisystem/about.html')

def login(request):
   return render(request, 'cisystem/login.html')

def contact(request):
   return render(request, 'cisystem/contact.html')

def birth_detail(request):
   return render(request, 'cisystem/birth_detail.html')

def death_detail(request):
   return render(request, 'cisystem/death_detail.html')

def late_registration(request):
   return render(request, 'cisystem/late_registration_detail.html')

def death_certificate(request):
    return render(request, 'cisystem/death_certificate.html')

def birth_certificate(request):
    return render(request, 'cisystem/birth_certificate.html')

def user_error_login(request):
   return render(request, 'cisystem/user_error_login.html')

class userProfileView(generic.DetailView):
    model = Birth
    template_name = 'cisystem/user_profile.html'

class birthcertificateView(generic.DetailView):
    model = Birth
    template_name = 'cisystem/birth_certificate.html'

class deathCertificateView(generic.DetailView):
    model = Death
    template_name = 'cisystem/death_certifcate.html'

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    type = request.POST.get('type')
    username = request.POST.get('username')
    password = request.POST.get('password')

    try:
        if type == 'birth':
            obj = Birth.objects.get(username=username, password=password)
            context = {'obj': obj}
            return render(request, 'cisystem/birth_certificate.html', context)

        else:
            death_obj = Death.objects.get(username=username, password=password)
            return render(request, 'cisystem/death_certificate.html', {'death_obj': death_obj})
    except:
        return render(request, 'cisystem/user_error_login.html')


class get_eligible_listView(generic.ListView):
    template_name = 'cisystem/eligible_list.html'
    context_object_name = 'eligible_list'

    def get_queryset(self):
        return Birth.objects.filter(is_eligible=True, child_age__gte=18)

class get_vital_statistics_View(generic.ListView):
    template_name = 'cisystem/vital_statistics.html'
    context_object_name = 'statistics'

    def get_queryset(self):
        return Birth.objects.all()

class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        birth = Birth.objects.all().count()
        death = Death.objects.all().count()
        is_eligible = Birth.objects.filter(is_eligible=True).count()
        total_population = Birth.objects.all().count() - Death.objects.all().count()
        aged_population = Birth.objects.filter(is_eligible=True, child_age__gte=70).count()
        under_aged_population = Birth.objects.filter(is_eligible=True, child_age__lte=18).count()

        labels = ["All birth", "Eligible Voter", "Death", "Total Population", "Aged 70+", "Under Aged below 18"]
        default_items = [birth, is_eligible, death, total_population, aged_population, under_aged_population]
        is_eligible = [is_eligible]
        data = {
                "labels": labels,
                "default": default_items,
                "is_eligible": is_eligible,
        }
        return Response(data)

cisystem/templates/cisystem/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Welcome to Civil Registration System</h1>
</body>
</html>

cisystem/templates/cisystem/birth_detail.html
{% extends 'cisystem/header.html' %}

{% block body %}
<h1>Birth detail page</h1>
{% endblock %}

cisystem/templates/cisystem/contact.html
<h1>Contact us here</h1>

cisystem/templates/cisystem/eligible_list.html
{% extends 'cisystem/header.html' %}
{% load static %}

{% block body %}
{% if eligible_list %}
<div class="container">
    <div class="eligible_title"><h4 class="title">Eligible List</h4></div>
<table class="table">
  <thead class="table-header">
    <tr>
      <th scope="col">Entry no</th>
      <th scope="col">Surname</th>
      <th scope="col">Other name</th>
      <th scope="col">Age</th>
      <th scope="col">Date of Birth</th>
      <th scope="col">Is Dead</th>
    </tr>
  </thead>
  <tbody>
      {% for eligible in eligible_list %}
    <tr>
      <th scope="row">{{eligible.entry_no}}</th>
      <td>{{eligible.surname_of_child}}</td>
      <td>{{eligible.other_name_of_child}}</td>
      <td>{{eligible.child_age}}</td>
      <td>{{eligible.date_of_birth}}</td>
      <td>{{eligible.is_dead}}</td>
    </tr>
  </tbody>
    {% endfor %}

</table>
 </div>
{% else %}
<p>No member of the population is eligible</p>
{% endif %}
{% endblock %}

cisystem/templates/cisystem/header.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static 'cisystem/css/style.css' %}" type="text/css">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Civil Registration System</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand active" href="{% url 'cisystem:index' %}">CRVSYSTEM</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cisystem:about' %}">About<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin Login</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'cisystem:login' %}">User Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cisystem:contact' %}">Contact</a>
      </li>
    </ul>
  </div>
</nav>

{% block body %}
{% endblock %}

 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

cisystem/templates/cisystem/index.html
{% extends 'cisystem/header.html'%}

{% block body %}

{% load static %}
<img src="{%  static 'cisystem/images/surgery.jpg' %}" class="background-image" alt="background image">
<h3 class="welcome">Welcome to Birth & Death Registration System</h3>
<p class="welcome-message">We carter for your birth registraion and death registrations.
    <br>We keep statistics of all birth and death records in Nigeria
</p>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-sm-4">
            <div class="card my-card">
                <img src="{%  static 'cisystem/images/newborn.jpg' %}" class="card-img-top" alt="new born baby">
                <div class="card-body">
                    <h5 class="card-title">Birth Registration</h5>
                    <p class="card-text">This shows the procedures for birth registration</p>
                    <a href="{% url 'cisystem:birth_detail' %}" class="btn btn-primary">More</a>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="card birth">
                <img src="{%  static 'cisystem/images/clinic.jpg' %}" class="card-img-top" alt="clinic">
                <div class="card-body">
                    <h5 class="card-title">Death Registration</h5>
                    <p class="card-text">This shows the procedures for death registration</p>
                    <a href="{% url 'cisystem:death_detail' %}" class="btn btn-primary">More</a>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="card my-card">
                <img src="{%  static 'cisystem/images/medical.jpg' %}" class="card-img-top" alt="medical">
                <div class="card-body">
                    <h5 class="card-title">Late Registration</h5>
                    <p class="card-text">This gives the general birth and death statistics in Nigeria</p>
                    <a href="{% url 'cisystem:late_registration' %}" class="btn btn-primary">More</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% include 'cisystem/footer.html'%}

{% endblock %}

cisystem/templates/cisystem/login.html
{% extends 'cisystem/header.html' %}

<!-- templates/registration/login.html -->
{% block body %}

{% if form.errors %}
<p>username or password not correct</p>
{% endif %}
<div class="container">
    <h3>Login</h3>

    <form method="post" action="{% url 'cisystem:user_login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        {# A more "HTML" way of creating the login form#}
        <div>
            <label>
                Birth:
                <input type="radio" name="type" value="birth" required>
            </label>
            <label>
                Death:
                <input type="radio" name="type" value="death" required>
            </label>
        </div>
        <div  class="form-group">
            <label for="username">Username:</label>
            <input type="text" name="username" class="form-control" placeholder="Username" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" class="form-control" placeholder="Password" required>
        </div>
        <input type="submit" name="" class="btn btn-primary" value="Login">
    </form>
</div>


{% for message in messages %}
<div id="error" hidden>
    <h3>{{message}}</h3>
</div>
{% endfor %}
{% endblock %}

cisystem/templates/cisystem/user_error_login.html
{% extends 'cisystem/header.html' %}
{% load static %}

{% block body %}
<div class="container error-page">
    <div class="alert alert-danger" role="alert">
        <h4>Sorry we can't access your profile at this time. Please contact your registrar for login access</h4>

    </div>
    <button class="btn btn-primary"><a class="try-again" href="{% url 'cisystem:login'%}">Try Again</a></button>
</div>

{% endblock %}

cisystem/templates/cisystem/vital_statistics.html
{% extends 'cisystem/header.html' %}
{% load static %}
<!-- Override extrahead to add Chart.js -->
{% block body %}
{% block jquery %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"/>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="{% static 'cisystem/css/style.css' %}" type="text/css"/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
<script>
var endpoint = '/api/chart/data/'
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)
    }
})
function setChart(){
    var ctx = document.getElementById("myChart");
    var ctx2 = document.getElementById("myChart2").getContext('2d');
    var myChart = new Chart(ctx2, {
    type: 'polarArea',
    data: {
        labels: labels,
        datasets: [{
            label: 'Vital Statistics',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        },
        legend:{
            display : true,
            position :'right',
        }
    }
});

// For a pie chart
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: labels,
        datasets: [{
            label: 'Vital Statistics',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        },
        legend:{
            display : true,
            position :'right',
        }
    }
});
}
// var ctx = document.getElementById("myChart");
{% endblock %}

</script>

{% block content %}
<div class="container">
   <h3 class="heading">Overview of Vital Statistics</h3>
    <div class='row' url-endpoint='{% url "cisystem:api_data" %}'>
            <div class="col-sm">
                <canvas id="myChart" width="400" height="400"></canvas>
            </div>
            <div class='col-sm'>
                <canvas id="myChart2" width="400" height="400"></canvas>
            </div>
    </div>
</div>
{% endblock %}
{% include 'cisystem/footer.html' %}
{% endblock %}